spring:
  datasource: 
     url: jdbc:mysql://localhost:3306/mydb?
     username: root
     password: Vy.&7N9BGfa1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
        